# -*- coding: utf-8 -*-
"""RAG pipeline POC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAhCNbayQqzt5HVTB_TeTUql1_zm3ikB
"""

!pip install requests==2.32.4 youtube-transcript-api yt-dlp

!pip install qdrant-client sentence-transformers

!pip install langchain langchain-community langchain-text-splitters

!pip install torch accelerate

import torch
from youtube_transcript_api import YouTubeTranscriptApi
from yt_dlp import YoutubeDL
from sentence_transformers import SentenceTransformer
from langchain_text_splitters import RecursiveCharacterTextSplitter
from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    VectorParams,
    PointStruct
)
import uuid
from langchain_core.documents import Document

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)
embedding_model = SentenceTransformer(
    "BAAI/bge-large-en-v1.5",
    device=device
)
print("Embedding model loaded")

yt_url='https://www.youtube.com/watch?v=r6EXZcTJyaA'
def extract_video_metadata(url):

    ydl_opts = {
        "quiet": True
    }
    with YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)
    metadata = {
        "video_id": info.get("id"),
        "title": info.get("title"),
        "description": info.get("description"),
        "channel": info.get("channel"),
        "view_count": info.get("view_count"),
        "like_count": info.get("like_count"),
        "duration": info.get("duration"),
        "upload_date": info.get("upload_date"),
        "tags": info.get("tags")
    }
    return metadata

yt_meta=extract_video_metadata(yt_url)
yt_meta

ytt_api = YouTubeTranscriptApi()
def extract_transcript(video_id):
    transcript = ytt_api.fetch(video_id)
    return transcript.to_raw_data()

video_id = yt_meta["video_id"]
transcript = extract_transcript(video_id)

transcript[:5]

def prepare_documents(transcript):
    documents = []
    for chunk in transcript:
        text = chunk["text"]
        start = chunk["start"]
        duration = chunk["duration"]
        end = round(start + duration,2)
        documents.append({
            "text": text,
            "start_time": start,
            "duration": duration,
            "end_time": end
        })
    return documents

documents = prepare_documents(transcript)
documents[:3]

def build_transcript_windows(documents, window_size = 1500):
    windows = []
    current_text = ""
    current_start = None
    current_end = None

    for doc in documents:
        text = doc["text"]
        start = doc["start_time"]
        end = doc["end_time"]
        if current_start is None:
            current_start = start

        current_text += " " + text
        current_end = end
        if len(current_text) >= window_size:
            windows.append({
                "text": current_text.strip(),
                "start_time": current_start,
                "end_time": current_end

            })
            current_text = ""
            current_start = None

    if current_text:
        windows.append({
            "text": current_text.strip(),
            "start_time": current_start,
            "end_time": current_end
        })

    return windows
windows = build_transcript_windows(documents)
len(windows), windows[0]

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=200,
    separators=[
        "\n\n",
        "\n",
        ". ",
        "! ",
        "? ",
        ", ",
        " "
    ])

def create_langchain_documents(windows):
    langchain_docs = []
    for window in windows:
        doc = Document(
            page_content=window["text"],
            metadata={
                "start_time": window["start_time"],
                "end_time": window["end_time"]
            })
        langchain_docs.append(doc)
    return langchain_docs

def split_documents_with_overlap(langchain_docs):
    split_docs = text_splitter.split_documents(
        langchain_docs
    )
    return split_docs

def convert_to_chunks(split_docs):
    chunks = []
    for doc in split_docs:
        chunks.append({
            "text": doc.page_content,
            "start_time": doc.metadata["start_time"],
            "end_time": doc.metadata["end_time"]
        })
    return chunks

langchain_docs = create_langchain_documents(windows)
split_docs = split_documents_with_overlap(langchain_docs)
chunks = convert_to_chunks(split_docs)
len(chunks),chunks[:3]

texts = [doc["text"] for doc in chunks]
embeddings = embedding_model.encode(
    texts,
    batch_size=30,
    show_progress_bar=True,
    convert_to_numpy=True
)

embeddings.shape

qdrant = QdrantClient(":memory:")

collection_name = "youtube_transcript"
qdrant.recreate_collection(
    collection_name=collection_name,
    vectors_config=VectorParams(
        size=embeddings.shape[1],
        distance=Distance.COSINE
    )
)

points = []
for idx, (doc, embedding) in enumerate(zip(chunks, embeddings)):
    point = PointStruct(
        id=str(uuid.uuid4()),
        vector=embedding.tolist(),
        payload={
            "text": doc["text"],
            "start_time": doc["start_time"],
            "end_time": doc["end_time"],
            "video_id": yt_meta["video_id"],
            "title": yt_meta["title"],
            "channel": yt_meta["channel"]
        }
    )
    points.append(point)

qdrant.upsert(
    collection_name=collection_name,
    points=points
)
print("Stored successfully")

query = "I need the timestamp of when he discusses about shaders"
query_embedding = embedding_model.encode(
    query,
    convert_to_numpy=True
)

results = qdrant.query_points(
    collection_name=collection_name,
    query=query_embedding.tolist(),
    limit=3,
    with_payload=True
)

results.dict()

